/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package f.project.view;

import java.awt.Color;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;

/**
 *
 * @author jvaldez
 */
public class ReportView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Informationview
     */
    public ReportView() {
        initComponents();
       this.getContentPane().setBackground( Color.decode("#FFFFFF") );
      
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reportes");
        setName("Report"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
